### ISSUE TITLE
Setup iceberg environment for testing

### ISSUE THREAD

**Issue by samansmink** [duckdb/duckdb_iceberg#20]
https://github.com/tabular-io/docker-spark-iceberg seems like a good fit for integrating into this extension for local development and CI. That way we have a way to test future REST catalog support in this extension

**Comment by Fokko** [comment]
Hey @samansmink Missed this one, but I'm happy to pick this one up and make it part of the build.

**Comment by samansmink** [comment]
hey @Fokko that would be great!

**Comment by Fokko** [comment]
Since #27 has been merged, this one can be closed @samansmink Thanks!
