### ISSUE TITLE
Support other catalogs (currently version-hint.text is required)

### ISSUE THREAD

**Issue by a-agmon** [duckdb/duckdb_iceberg#22]
Just want to confirm:  seems that the extension currently only supports HDFS catalog as it is looking for the version-hint.text. 
Im using the Glue Catalog and dont have version-hint.text
any way to override this?

**Comment by samansmink** [comment]
Hey @a-agmon, with other issues asking for more catalogs already existing, including the Glue catalog you mention here, i think this one can be closed as a duplicate.

The current workaround is to use external tooling to read the catalog, then pass the direct link to the version file to the iceberg scan as described in https://github.com/duckdb/duckdb_iceberg/pull/18
