### ISSUE TITLE
Unable to read complex data types(e.g. Map, Struct) after upgrading to latest (0.10.0) version

### ISSUE THREAD

**Issue by devendrasr** [duckdb/duckdb_iceberg#41]
The extension is able to read complex data types using duckdb 0.9.0 - 

![image](https://github.com/duckdb/duckdb_iceberg/assets/3923999/b3f09161-ed75-4121-bdfb-2228c7629a1e)

We could not read complex data types after upgrading to duckdb 0.10.0 - 

![image](https://github.com/duckdb/duckdb_iceberg/assets/3923999/c8ffa200-472a-47d0-bb72-f29cf780a234)

The database is throwing below error - 

```
Error: IO Error: Invalid field found while parsing field: type
```

**Comment by Fokko** [comment]
Thanks for reporting this! I think it is a duplicate of https://github.com/duckdb/duckdb_iceberg/issues/39

**Comment by devendrasr** [comment]
Yes, i ran into #39 after adding a temp workaround for this one.

**Comment by harel-e** [comment]
@devendrasr Can you provide more details on how you overcame the issue? How did you disable schema parsing? Thanks

**Comment by devendrasr** [comment]
@harel-e  i made few changes like this - https://github.com/devendrasr/duckdb_iceberg/commit/d9e5d720b319e4e474a39373d8d43781a0a3b028

**Comment by harel-e** [comment]
@devendrasr will PR#43 that you created solve this issue? Thank you

**Comment by devendrasr** [comment]
It just allows you to skip schema inference and fallback to parquet extension to infer schema. In this way we are able to read complex data types via iceberg extension.

**Comment by harel-e** [comment]
@devendrasr - I'd like to test your changes locally, especially with issue #39.  Is it possible for you to provide a binary since I'm having issues building DuckDB locally? thanks.

**Comment by devendrasr** [comment]
@harel-e  You can try them out using - 

``` 
docker run --rm --name=duckdb -it devendrasr/duckdb:0.0.1 bash
```

**Comment by harel-e** [comment]
@devendrasr - thank you for providing an image for testing.
I tried the scenario described here: https://github.com/duckdb/duckdb_iceberg/issues/39#issuecomment-1943244889
Unfortunately, it still fails with:

D SELECT * FROM iceberg_scan('data/iceberg/lineitem_iceberg', allow_moved_paths = true);
Error: IO Error: Invalid field found while parsing field: required

I understand you were not trying to address issue #39. I thought they were somewhat related.

Thanks again.

**Comment by harel-e** [comment]
My bad, I forgot to add skip_schema_inference = true.
I tested it again with both lineitem data and my own dataset (minio/nessie) and it works !
Thank you very much !  

I'll wait for the PR to be merged.

**Comment by devendrasr** [comment]
The issue has been resolved in pull request - https://github.com/duckdb/duckdb_iceberg/pull/45

The request is now merged in trunk. Closing this one.
