### ISSUE TITLE
Can't seem to read a table (unexpected error, crashes JVM processes)

### ISSUE THREAD

**Issue by shanielh** [duckdb/duckdb_iceberg#86]
I tried both using DuckDB 1.1.3 (Latest as of this post) and 1.2.0-SNAPSHOT (using DBeaver). 

Reproduction:

1. Download and open the [Archive.zip](https://github.com/user-attachments/files/17969129/Archive.zip) to `/tmp/default_storage_173276977134208/tables/00000000-0000-0000-0000-00000ee128fc` 
2. Run the following SQL commands : 

```sql
INSTALL iceberg;
LOAD iceberg;

SELECT * FROM iceberg_scan('/tmp/default_storage_173276977134208/tables/00000000-0000-0000-0000-00000ee128fc/metadata/00015-49f45d85-a345-4fc3-92f1-1e0c8b1950ef.gz.metadata.json');
```

[crash_report.log](https://github.com/user-attachments/files/17969155/crash_report.log)

**Comment by shanielh** [comment]
I had two errors after resolving this one (I forgot to set `METADATA_COMPRESSION_CODEC='gzip'`):

1. No supports for upserts (positional / equality deletes in Iceberg Spec V2) - https://github.com/duckdb/duckdb_iceberg/issues/67, https://github.com/duckdb/duckdb_iceberg/issues/5
2. Tables on local file system didn't work (https://github.com/duckdb/duckdb_iceberg/issues/38), It seems like the fix is to modify `FileSystem::ExpandPath` to : 

```cpp
string FileSystem::ExpandPath(const string &path, optional_ptr<FileOpener> opener) {
	auto file_path = path;
	auto file_prefix = "file://";
	if (StringUtil::StartsWith(path, file_prefix)) {
		file_path = path.substr(strlen(file_prefix));
	}

	if (file_path.empty()) {
		return file_path;
	}
	if (file_path[0] == '~') {
		return GetHomeDirectory(opener) + file_path.substr(1);
	}
	return file_path;
}
```

I'm closing this issue as it's no longer needed since there are other issues / PRs.

**Comment by jasonf20** [comment]
This is a real issue as it crashes instead of throwing and indicative error (or automatically handling compression)
